const express = require("express");
const path = require("path");
require("dotenv").config();
const { connect } = require("./lib/database");
const {
  getRecipiesMongo,
  getRecipeByNameMongo,
  insertRecipeInWeekMongo,
} = require("./lib/connectRecipes");
const {
  getRecipeByNameWeekMongo,
  deleteRecipeInWeekMongo,
  getWeekMongo,
  updateRecipeInWeekMongo,
} = require("./lib/connectWeek");
const {
  getShoppingListMongo,
  insertShoppingItemsMongo,
  deleteShoppingItemMongo,
} = require("./lib/connectShoppingList");
const { deleteAllElements } = require("./lib/helpFunctions");

const port = process.env.PORT || 3001;
const app = express();
app.use(express.json());

const collections = ["recipes", "shoppingList", "week"];
collections.forEach((collection) => {
  app.route(`/api/${collection}`).delete(async (req, res) => {
    try {
      await deleteAllElements(`${collection}`);
      res.send(`Successfully deleted content from ${collection}`);
    } catch (error) {
      console.error(error);
      res.status(500).send("An internal server error occured");
    }
  });
});

app.get("/api/recipes/:recipeName", async (req, res) => {
  const recipeName = req.params["recipeName"];
  try {
    const getName = await getRecipeByNameMongo(recipeName);
    if (!getName) {
      res.status(404).send("Recipe is not in Database");
      return;
    }
    res.send(getName);
  } catch (error) {
    console.error(error);
    res.status(500).send("An internal server error occured");
  }
});

app.get("/api/recipes", async (req, res) => {
  try {
    const recipeList = await getRecipiesMongo();
    if (!recipeList) {
      res.status(404).send("Could not find any recipies");
      return;
    }
    res.send(recipeList);
  } catch (error) {
    console.error(error);
    res.status(500).send("An internal server error occured");
  }
});

app
  .route("/api/week/recipe/:RecipeName")
  .get(async (req, res) => {
    const { RecipeName } = req.params;
    try {
      const getName = await getRecipeByNameWeekMongo(RecipeName);
      if (getName === null) {
        res.send(false);
        return;
      }
      res.send(true);
    } catch (error) {
      console.error(error);
      res.status(500).send("An internal sever error occured");
    }
  })
  .delete(async (req, res) => {
    const { RecipeName } = req.params;
    try {
      await deleteRecipeInWeekMongo(RecipeName);
      res.send(`Successfully deleted ${RecipeName} from week`);
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .send("An unexpected error occured. Please try again later!");
    }
  });

app.patch("/api/week/:id", async (req, res) => {
  const id = req.params["id"];
  const date = req.body;
  try {
    await updateRecipeInWeekMongo(date, id);
    res.send(`Successfully updated ${date}`);
  } catch (error) {
    console.error(error);
    res
      .status(500)
      .send("An unexpected error occured. Please try again later!");
  }
});

app
  .route("/api/week")
  .get(async (req, res) => {
    try {
      const weekList = await getWeekMongo();
      if (!weekList) {
        res.status(404).send("Could not find any recipies");
        return;
      }
      res.send(weekList);
    } catch (error) {
      console.error(error);
      res.status(500).send("An internal server error occured");
    }
  })
  //this post-method could go into the forEachLoop, but doesn't make a difference down here or up there right now
  .post(async (req, res) => {
    const recipe = req.body;
    try {
      await insertRecipeInWeekMongo(recipe);
      res.send(`Successfully inserted ${recipe}`);
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .send("An unexpected error occured. Please try again later!");
    }
  });

app.delete("/api/shoppingItems/:item", async (req, res) => {
  const shoppingItem = req.params["item"];
  try {
    await deleteShoppingItemMongo(shoppingItem);
    res.send("Successfully deleted Shopping Item");
  } catch (error) {
    console.error(error);
    res
      .status(500)
      .send("An unexpected error occured. Please try again later!");
  }
});

app
  .route("/api/shoppingItems")
  //this get-method could go into the forEachLoop, but doesn't make a difference down here or up there right now
  .get(async (req, res) => {
    try {
      const shoppingItems = await getShoppingListMongo();
      if (!shoppingItems) {
        res.status(404).send("Could not find any shoppingItems");
        return;
      }
      res.send(shoppingItems);
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .send("An internal server error occured. Please try again later");
    }
  })
  .post(async (req, res) => {
    try {
      const newShopppingItems = Array.isArray(req.body) ? req.body : [req.body];
      await insertShoppingItemsMongo(newShopppingItems);
      res.send(`Successfully inserted shopping items`);
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .send("An unexpected error occured. Please try again later!");
    }
  });

app.use(express.static(path.join(__dirname, "client/build")));

app.get("*", (req, res) => {
  res.sendFile(path.join(__dirname, "client/build", "index.html"));
});

async function run() {
  console.log("Connecting to Database...");
  await connect(process.env.DB_URI, process.env.DB_DBNAME);
  console.log("Connected to databaseðŸŽ„");

  app.listen(port, () => {
    console.log(`Appeatit API listening at http://localhost:${port}`);
  });
}
run();
